# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-24 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheeseIt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cheese',
            name='name',
            field=models.CharField(default='Cheeeeeeeese!', max_length=64, verbose_name='Name'),
        ),
    ]
