# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheeseIt', '0003_auto_20171117_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cheese',
            name='startTemp',
            field=models.IntegerField(default=86),
        ),
    ]
