# Generated by Django 2.0 on 2018-02-26 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheeseIt', '0004_auto_20171119_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='cheese',
            name='mTemp',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='cheese',
            name='wTemp',
            field=models.IntegerField(default=1),
        ),
    ]
